# Generated by Django 2.1.7 on 2019-05-19 06:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('connectivity', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Isp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=40, unique=True)),
                ('scrupulous', models.BooleanField()),
            ],
        ),
        migrations.RemoveField(
            model_name='school',
            name='isp',
        ),
        migrations.AlterField(
            model_name='school',
            name='ip',
            field=models.CharField(max_length=16, unique=True),
        ),
        migrations.AddField(
            model_name='school',
            name='Isp',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='connectivity.Isp'),
        ),
    ]
