# Generated by Django 2.1.7 on 2019-05-19 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('connectivity', '0002_auto_20190519_0231'),
    ]

    operations = [
        migrations.AlterField(
            model_name='school',
            name='ip',
            field=models.CharField(max_length=16),
        ),
    ]
