# Generated by Django 2.1.7 on 2019-05-31 07:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('connectivity', '0003_auto_20190519_0238'),
    ]

    operations = [
        migrations.CreateModel(
            name='Prob',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bandwidth', models.FloatField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='school',
            name='Isp',
        ),
        migrations.RemoveField(
            model_name='school',
            name='connectivity',
        ),
        migrations.RemoveField(
            model_name='school',
            name='name',
        ),
        migrations.AddField(
            model_name='isp',
            name='name',
            field=models.CharField(max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='school',
            name='city',
            field=models.CharField(max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='school',
            name='country',
            field=models.CharField(max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='school',
            name='lat',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='school',
            name='lon',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='school',
            name='org',
            field=models.CharField(max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='school',
            name='region',
            field=models.CharField(max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='school',
            name='timezone',
            field=models.CharField(max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='school',
            name='zip',
            field=models.CharField(max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='isp',
            name='address',
            field=models.CharField(max_length=40),
        ),
        migrations.AlterField(
            model_name='school',
            name='ip',
            field=models.CharField(max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='prob',
            name='isp',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='connectivity.Isp'),
        ),
        migrations.AddField(
            model_name='prob',
            name='school',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='connectivity.School'),
        ),
    ]
